core/urls.py
from django.urls import path, include
from core import views
from core import views as core_views

app_name = "core"

urlpatterns = [

    #comman
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"),
    path("shop/", views.ShopView.as_view(), name="shop"),


    # User
    path("user/profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("user/profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("user/profile/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("user/profile/<int:pk>/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    #path("user/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    path("user/dashboard/", views.DashboardView.as_view(), name="dashboard"),


    #cart
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="cart_add"),
    path("cart/checkout/", views.CheckoutView.as_view(), name="checkout"),


    #product
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/<int:pk>/detail/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product/category", views.CategoryListView.as_view(), name="category_list"),
    path("product/category/<int:pk>/product/", views.ProductListByCategory.as_view(), name="product_by_category"),
    path("product/<int:pk>/review/", views.ProductReviewAddView.as_view(), name="add_product_review"),

    #product search
    path("product/search/", core_views.SearchView.as_view(), name= "product_search"),


    # Wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist_list"),
    path("wishlist/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlist/<int:pk>/", views.WishlistDetailView.as_view(), name="wishlist_detail"),
    path("wishlist/add/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="add_to_wishlist"),
    path("wishlist/remove/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="remove_from_wishlist"),

    #registration
    path("user/signup/", views.RegistrationView.as_view(), name="signup"),
    path("user/login/", views.LoginView.as_view(), name="login"),
    path("user/logout/", views.LogoutView.as_view(), name="logout"),
    
    # Password Reset
    path("user/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("user/password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("user/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user/reset/done/", views.PasswordResetConfirmView.as_view(), name="password_reset_complete"),

    #order
    path("order/", views.OrderView.as_view(), name="order"),
    path("order/history/", views.OrderHistoryView.as_view(), name="order_history"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_detail"),

  # Payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    path("paymentlist/", views.PaymentListView.as_view(), name="payment_list"),
    path("payment/response/", views.payment_handler, name="payment_handler"),


    

]

ecart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path('accounts/', include('allauth.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/user/profile/create.html
{% extends 'base.html' %} {% block content %}

<!-- cart -->
<div class="cart-section">
  <div class="container py-5">
    <div class="row justify-content-center mt-3 mb-3">
      <div class="col-auto">
        <div class="heading-1">
          <h1 class="text-center">Create Profile</h1>
          <div class="hl"></div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center g-3 align-items-lg-start">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %} {{form.as_p}}
              <button
                type="submit"
                class="btn btn-dark rounded-pill px-4 py-3 text-uppercase"
              >
                Create
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end cart -->
{% endblock content %}

templates/user/profile/detail.html
{% extends "base.html" %} {% block content %}
<section>
  <div class="container py-5">
    <div class="row justify-content-center mt-3 mb-3">
      <div class="col-auto">
        <div class="heading-1">
          <h1 class="text-center">Profile Details</h1>
          <div class="hl"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <img src="{{object.image.url}}" alt="" class="card-img-top" />
          
          <a href="{{profile_form.instance.image.url}}"  class="btn btn-primary" download >Downlod This Image<i class="fa-solid fa-download"></i></a>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title fw-bold">{{object}}</h4>
            <div class="hr m-0 mb-3"></div>
            <p class="card-text">First Name: {{object.first_name}}</p>
            <p class="card-text">Last Name: {{object.last_name}}</p>
            <p class="card-text">Gender: {{object.gender}}</p>
            <div class="mb-3">
              <p class="card-title">Addresses:</p>

              {% for address in object.addresses.all %}
              <p class="card-text">{{forloop.counter}}) {{address}}</p>
              {% empty %}
              <p class="card-text">
                Address:
                <a
                  href="{% url 'core:address_create' object.id %}"
                  class="link-primary"
                >
                  Create
                </a>
              </p>
              {% endfor %}
            </div>

            <a
              href="{% url 'core:profile_update' object.id %}"
              class="btn btn-dark rounded-pill py-3 px-4"
              >Update</a
            >
            
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/user/profile/update.html
{% extends 'base.html' %} {% block content %}

<!-- cart -->
<div class="cart-section">
  <div class="container py-5">
    <div class="row justify-content-center mt-3 mb-3">
      <div class="col-auto">
        <div class="heading-1">
          <h1 class="text-center">Update Profile</h1>
          <div class="hl"></div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center g-3 align-items-lg-start">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %} {{form.as_p}}
              <button
                type="submit"
                class="btn btn-dark rounded-pill px-4 py-3 text-uppercase"
              >
                Update
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end cart -->
{% endblock content %}