core/urls.py
from django.urls import path, include
from core import views
from core import views as core_views

app_name = "core"

urlpatterns = [

    #comman
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"),
    path("shop/", views.ShopView.as_view(), name="shop"),


    # User
    path("user/profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("user/profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("user/profile/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("user/profile/<int:pk>/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    #path("user/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    path("user/dashboard/", views.DashboardView.as_view(), name="dashboard"),


    #cart
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="cart_add"),
    path("cart/checkout/", views.CheckoutView.as_view(), name="checkout"),


    #product
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/<int:pk>/detail/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product/category", views.CategoryListView.as_view(), name="category_list"),
    path("product/category/<int:pk>/product/", views.ProductListByCategory.as_view(), name="product_by_category"),
    path("product/<int:pk>/review/", views.ProductReviewAddView.as_view(), name="add_product_review"),

    #product search
    path("product/search/", core_views.SearchView.as_view(), name= "product_search"),


    # Wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist_list"),
    path("wishlist/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlist/<int:pk>/", views.WishlistDetailView.as_view(), name="wishlist_detail"),
    path("wishlist/add/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="add_to_wishlist"),
    path("wishlist/remove/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="remove_from_wishlist"),

    #registration
    path("user/signup/", views.RegistrationView.as_view(), name="signup"),
    path("user/login/", views.LoginView.as_view(), name="login"),
    path("user/logout/", views.LogoutView.as_view(), name="logout"),
    
    # Password Reset
    path("user/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("user/password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("user/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user/reset/done/", views.PasswordResetConfirmView.as_view(), name="password_reset_complete"),

    #order
    path("order/", views.OrderView.as_view(), name="order"),
    path("order/history/", views.OrderHistoryView.as_view(), name="order_history"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_detail"),

  # Payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    path("paymentlist/", views.PaymentListView.as_view(), name="payment_list"),
    path("payment/response/", views.payment_handler, name="payment_handler"),


    

]

ecart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path('accounts/', include('allauth.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/cart_item_listing.html
{% for form in formset %}
<tr class="table-body-row">
  <td class="product-remove">
    <button class="btn border-0">
      <i class="far fa-window-close"></i>
    </button>
  </td>
  <td class="product-image">
    <img src="{{form.instance.product.image.url}}" alt="" />
  </td>
  <td class="product-name">{{form.instance.product}}</td>
  <td class="product-price">INR {{form.instance.product.price}}</td>
  <td class="product-quantity">{{form.quantity}}</td>
  <td class="product-total">INR {{form.instance.total}}</td>
</tr>
{% endfor %}

templates/includes/footer.html
{% load static %}

<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <div class="footer-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <div class="footer-box about-widget">
            <h2 class="widget-title">About us</h2>
            <p>
              The main allure of E-shopping is that consumers can find and
              purchase items they need (which are then shipped to their front
              door) without ever leaving the house. E-shopping was introduced to
              bring convenience to the lives of people.
            </p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-box get-in-touch">
            <h2 class="widget-title">Get in Touch</h2>
            <p>34/8, East Hukupara, Gifirtok, Sadan.</p>
            <p>www.eshopping.com</p>
            <p>+00 111 222 3333</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-box pages">
            <h2 class="widget-title">Pages</h2>

            <p><a href="{% url 'core:home' %}">Home</a></p>
            <p><a href="{% url 'core:about' %}">About</a></p>
            <p><a href="{% url 'core:shop' %}">Shop</a></p>
            <!--<p><a href="{% url 'core:cart' %}">Cart</a></p>-->
            <p><a href="{% url 'core:category_list' %}">Categories</a></p>
            <p><a href="{% url 'core:feedback_create' %}">Contact us</a></p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-box subscribe">
            <h2 class="widget-title">Subscribe</h2>
            <p>Sent your latest updates....</p>
            <form action="#">
              <input type="email" placeholder="Email" />
              <button  id = "submit"  class="btn btn-primary" type="submit">
                <i class="fa-solid fa-paper-plane"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">eshopping.com</a>
  </div>
  <!-- Copyright -->
</footer>

templates/includes/message.html
{% if messages %}
<div class="messages">
  {% for message in messages %}
  <div
    class="alert {{ message.tags }} alert-dismissible show"
    role="alert"
  >
    {{ message }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %}
</div>

{% endif %}

templates/includes/navbar.html
{% load static %}
<!-- header start -->
<nav
  class="navbar navbar-expand-lg bg-dark navbar-dark sticky-top mb-0 shadow-sm"
>
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="#">E-Shopping </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav align-items-lg-center w-100">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'core:home' %}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:about' %}">About</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:feedback_create' %}"
            >Contact Us</a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:shop' %}">Shop</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:category_list' %}"
            >Categories</a
          >
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:cart' %}">Cart</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <div class="d-inline-block position-relative">
              <i class="fa-solid fa-cart-shopping"></i>
              <span
                class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
              >
                {{cart.items|length|default:"0"}}
                <span class="visually-hidden">unread messages</span>
              </span>
            </div>
          </a>

          <ul class="dropdown-menu m-0">
            <li class="p-3">
              <table
                class="table caption-top table-borderless table-striped mb-0 align-middle text-center"
              >
                <caption>
                  List of Products
                </caption>

                <thead class="">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Total</th>
                  </tr>
                </thead>
                <tbody class="table-group-divider">
                  {% for item in cart.items %}
                  <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td class="text-left text-nowrap">
                      <a
                        class="link-primary"
                        href="{% url 'core:product_detail' item.product.id %}"
                        >{{item.product.name}}</a
                      >
                    </td>
                    <td>{{item.product.price}}</td>
                    <td>{{item.quantity}}</td>
                    <td class="text-right">{{item.total}}</td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td class="text-left" colspan="5">Nothing found!</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{user}}
          </a>
          <ul class="dropdown-menu">
            
            {% if  user.has_profile %}
            <li>
              <a
                class="dropdown-item"
                href="{% url 'core:profile_detail' user.profilemodel.id %}"
                >Profile</a
              >
            </li>
            {% else %}
            <li>
              <a class="dropdown-item" href="{% url 'core:profile_create' %}"
                >Profile</a
              >
            </li>
            {% endif %}

            <li>
              <a class="dropdown-item" href="{% url 'core:dashboard' %}"
                >Dashboard</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:order_history' %}"
                >Order History</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:wishlist_list' %}"
                >Wishlist</a
              >
            </li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a>
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:signup' %}">Sign Up</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:login' %}">Login</a>
        </li>

        {% endif %}

        <li class="nav-item ms-lg-auto">
          {% csrf_token %}
          <form class="d-flex" role="search" action="{% url 'core:product_search' %}">
            <input
              class="form-control me-2"
              type="search"
              name="q"
              placeholder="Search for products"
              aria-label="Search"
            />
            <button class="btn btn-primary" type="submit">
              <i class="fa-solid fa-search"></i>
            </button>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/scripts.html
{% load static %}

<script src="{% static 'bootstrap-5.2.1-dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'fontawesome-free-6.2.0-web/js/all.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

templates/includes/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'bootstrap-5.2.1-dist/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome-free-6.2.0-web/css/all.css' %}">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">