core/urls.py
from django.urls import path, include
from core import views
from core import views as core_views

app_name = "core"

urlpatterns = [

    #comman
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"),
    path("shop/", views.ShopView.as_view(), name="shop"),


    # User
    path("user/profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("user/profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("user/profile/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("user/profile/<int:pk>/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    #path("user/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    path("user/dashboard/", views.DashboardView.as_view(), name="dashboard"),


    #cart
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="cart_add"),
    path("cart/checkout/", views.CheckoutView.as_view(), name="checkout"),


    #product
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/<int:pk>/detail/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product/category", views.CategoryListView.as_view(), name="category_list"),
    path("product/category/<int:pk>/product/", views.ProductListByCategory.as_view(), name="product_by_category"),
    path("product/<int:pk>/review/", views.ProductReviewAddView.as_view(), name="add_product_review"),

    #product search
    path("product/search/", core_views.SearchView.as_view(), name= "product_search"),


    # Wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist_list"),
    path("wishlist/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlist/<int:pk>/", views.WishlistDetailView.as_view(), name="wishlist_detail"),
    path("wishlist/add/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="add_to_wishlist"),
    path("wishlist/remove/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="remove_from_wishlist"),

    #registration
    path("user/signup/", views.RegistrationView.as_view(), name="signup"),
    path("user/login/", views.LoginView.as_view(), name="login"),
    path("user/logout/", views.LogoutView.as_view(), name="logout"),
    
    # Password Reset
    path("user/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("user/password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("user/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user/reset/done/", views.PasswordResetConfirmView.as_view(), name="password_reset_complete"),

    #order
    path("order/", views.OrderView.as_view(), name="order"),
    path("order/history/", views.OrderHistoryView.as_view(), name="order_history"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_detail"),

  # Payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    path("paymentlist/", views.PaymentListView.as_view(), name="payment_list"),
    path("payment/response/", views.payment_handler, name="payment_handler"),


    

]

ecart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path('accounts/', include('allauth.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/models.py
from django.db import models

# Create your models here.

shop/forms.py
from django import forms

templates/shop/category_list.html
{% extends 'base.html' %} {% block content %}

<!-- categories -->
<section class="vh-100">
  <div class="container py-5">
    <div class="row justify-content-center mt-3 mb-3">
      <div class="col-auto">
        <div class="heading-1">
          <h1 class="text-center">Categories</h1>
          <div class="hl"></div>
        </div>
      </div>
    </div>
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3 category-lists">
      {% for category in categories %}

      <div class="col-auto">
        <div class="card" style="height: 75px; width: 200px">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h6 class="card-title first-letter-danger">
                <a href="{% url 'core:product_by_category' category.id %}" class="link-dark">
                {{category.name|upper}} </a>
            </h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </div>
      {% empty %}
      <h4>Nothing Found!!</h4>
      {% endfor %}
    </div>

    <div class="row">
      <div class="col-lg-12 text-center">
        <div class="pagination-wrap">
          <ul>
            {% if page_obj.has_previous %}
            <li><a href="?page=1">First</a></li>

            <li>
              <a href="?page={{ page_obj.previous_page_number }}"
                >&laquo; Prev</a
              >
            </li>

            {% endif %}

            <li>
              <a class="active" href="#">{{ page_obj.number|default:0 }}</a>
            </li>

            {% if page_obj.has_next %}

            <li>
              <a href="?page={{ page_obj.next_page_number }}">&raquo; Next</a>
            </li>
            <li>
              <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>

</section>
<!-- end products -->
{% endblock content %}

templates/shop/checkout.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- check out section -->
<section class="checkout-section">
  <div class="container py-5">
    <div class="row justify-content-center mt-3 mb-3">
      <div class="col-auto">
        <div class="heading-1">
          <h1 class="text-center">Checkout</h1>
          <div class="hl"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 order-lg-1 order-2">
        <form method="post">
          {% csrf_token %}
          <div class="checkout-accordion-wrap">
            <div class="accordion" id="accordionExample">
              <!-- Billing address start-->
              <div class="card single-accordion">
                <div class="card-header" id="headingOne">
                  <h5 class="mb-0">
                    <button
<<<<<<< HEAD
                      class="btn btn-dark rounded-pill px-4 py-3"
=======
                      class="btn btn-link"
>>>>>>> refs/remotes/origin/main
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapseOne"
                      aria-expanded="true"
                      aria-controls="collapseOne"
                    >
                      {{billing_form.name}}
                    </button>
                  </h5>
                </div>
                <div
                  id="collapseOne"
                  class="accordion-collapse collapse show"
                  aria-labelledby="headingOne"
                  data-bs-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div id="billingAddressForm">
                      <table
                        class="table table-borderless table-hover align-middle"
                      >
                        <tbody>
                          {{billing_form.as_table}}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Billing address end -->

              <!-- Shipping address start -->
              <div class="card single-accordion">
                <div class="card-header" id="headingTwo">
                  <h5 class="mb-0">
                    <button
<<<<<<< HEAD
                      class="btn btn-dark rounded-pill px-4 py-3"
=======
                      class="btn btn-link"
>>>>>>> refs/remotes/origin/main
                      type="button"
                      data-bs-toggle="collapse"
                      data-bs-target="#collapseTwo"
                      aria-expanded="true"
                      aria-controls="collapseTwo"
                    >
                      {{shipping_form.name}}
                    </button>
                  </h5>
                </div>
                <div
                  id="collapseTwo"
                  class="accordion-collapse collapse"
                  aria-labelledby="headingTwo"
                  data-bs-parent="#accordionExample"
                >
                  <div class="card-body">
                    <div id="shippingForm">
                      <table class="table table-borderless align-middle">
                        <tbody>
                          {{shipping_form.as_table}}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Shipping address end -->

              <!-- Place order button start -->
              <button
                type="submit"
<<<<<<< HEAD
                class="btn btn-dark rounded-pill px-4 py-3"
=======
                class="btn btn-cart rounded-5 my-3 px-4 py-3"
>>>>>>> refs/remotes/origin/main
                id="orderPlaceBtn"
              >
                Place Order
              </button>
              <!-- Place order button end -->
            </div>
          </div>
        </form>
      </div>

      <div class="col-lg-4 mb-3 order-lg-2 order-1">
        <div class="card">
          <div class="card-body">
            <table class="table caption-top table-hover">
              <caption>
                Your order Details
              </caption>
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Price</th>
                </tr>
              </thead>
              <tbody class="table-group-divider">
                {% for item in cart.items %}
                <tr>
                  <td>{{item.product.name}}</td>
                  <td>INR {{item.total}}</td>
                </tr>
                {% endfor %}

                <tr>
                  <td>Delivery Charge</td>
                  <td>INR 50</td>
                </tr>

                <tr class="fw-bold">
                  <td>Subtotal</td>
                  <td>INR {{cart.total}}</td>
                </tr>

                <tr class="fw-bold">
                  <td>Total</td>
                  <td>INR {{cart.total|add:"50"}}.00</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end check out section -->

{% endblock content %}

templates/shop/order.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<section class="vh-100">
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Orders</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3 justify-content-center">
    {% for order in orders %}

    <div class="col-auto">
      <a href="{% url 'core:order_detail' order.id %}" class="link-dark">
        <div class="card">
          <div class="card-body">
            <h6 class="card-title">{{order.id|upper}}</h6>
            <p class="card-text">INR {{order.amount}}</p>
            <ul>
              {% for item in order.cart.items %}

              <li>{{item}}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </a>
    </div>
    {% empty %}
    <h4>Nothing Found!!</h4>
    {% endfor %}
  </div>
</div>
</section>
<!-- end products -->
{% endblock content %}

templates/shop/order_confirmed.html
{% extends 'base.html' %} {% block content %}
<h3 class="text-success">Order placed successfully!</h3>
<a href="{% url 'core:home' %}">Back to home page</a>
{% endblock content %}

templates/shop/order_failed.html
{% extends 'base.html' %} {% block content %}
<h3 class="text-danger">Order failed!</h3>
{% endblock content %}

templates/shop/order_history.html
{% extends 'base.html' %} {% block content %}

<!-- order history -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Order History</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Order ID</th>
            <th scope="col">Payment ID</th>
            <th scope="col">Payment Status</th>
            <th scope="col">Total</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for order in orders %}
          <tr>
            {% for payment in order.payment_set.all %}
            <td scope="row">{{forloop.parentloop.counter}}</td>
            <td scope="row">
              <a href="{% url 'core:order_detail' order.id %}">{{order.id}}</a>
            </td>
            <td scope="row">{{payment.id}}</td>
            <td scope="row">{{payment.status}}</td>
            <td scope="row">
              <span class="badge rounded-pill text-bg-info h6 px-4 py-2">
                INR {{order.amount}}
              </span>
            </td>
            {% empty %}
            <td scope="row">{{forloop.counter}}</td>
            <td scope="row">
              <a href="{% url 'core:order_detail' order.id %}">{{order.id}}</a>
            </td>
            <td scope="row">N/A</td>
            <td scope="row">N/A</td>
            <td scope="row">
              <span class="badge rounded-pill text-bg-info h6 px-4 py-2">
                INR {{order.amount}}
              </span>
            </td>
            {% endfor %}
          </tr>
          {% empty %}
          <tr class="text-center">
            <td colspan="5">
              <h3>Sorry!</h3>
              <p>You don't have any order to show!</p>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <a href="{% url 'core:shop' %}" class="btn btn-dark rounded-pill px-4 py-2">Shop</a>
    </div>
  </div>
</div>
<!-- end order history -->
{% endblock content %}

templates/shop/product_detail.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Product Details</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row g-2">
    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <img src="{{product.image.url}}" alt="..." class="card-img" />
        </div>
      </div>
    </div>
    <div class="col-lg-8 px-lg-4">
      <table class="table table-borderless table-hover">
        <thead></thead>
        <tbody>
          <tr>
            <th >Name</th>
            <td>{{product.name}}</td>
          </tr>
          <tr>
            <th>Description</th>
            <td>{{product.description}}</td>
          </tr>
          <tr>
            <th>Price</th>
            <td>INR {{product.price}}</td>
          </tr>
          <tr>
            <th>Category</th>
            <td>{{product.category}}</td>
          </tr>
          <tr class="text-nowrap">
            <th>Last Updated</th>
            <td>{{product.updated_on|date}}</td>
          </tr>
          <tr>
            <th>Rating</th>
            <td>{{product.reviewmodel.rating}}</td>
          </tr>
          <tr>
            <td class="" colspan="2">
              <a
                href="{% url 'core:cart_add' product.id%}"
                class="btn btn-dark border-0 rounded-5 py-3 px-4"
              >
                <i class="fa-solid fa-shopping-cart"></i> Add to Cart
              </a>

              <a href="{% url 'core:add_to_wishlist' product.id %}" class="btn btn-dark border-0 rounded-5 py-3 px-4">
                <i class="fa-solid fa-heart"></i>
                Add to wishlist
              </a>
              <a href="{% url 'core:add_product_review' product.id %}" class="btn btn-dark rounded-5 px-4 py-3">
                <i class="fa-solid fa-star"></i>
                Add Review
              </a>
              <a
                href="{% url 'core:shop' %}"
                class="btn btn-dark rounded-5 px-4 py-3"
              >
                <i class="fa-solid fa-arrow-left"></i>
                Shop
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- end products -->
{% endblock content %}

templates/shop/product_list.html
<!-- product section -->
<div class="container py-2">
  <div class="row row-cols-lg-4 g-3">
    {% for product in products %}
    <div class="col">
      <div class="card">
        <a href="{% url 'core:product_detail' product.id %}"
          ><img
            src="{{product.image.url}}"
            class="card-img-top"
            height="200px"
            alt=""
        /></a>

        <div class="card-body">
          <h3>{{product.name}}</h3>
          <p class="product-price">
            <span>Per {{product.unit}}</span>
            <i class="fa-solid fa-inr"></i>
            {{product.price}}
          </p>
          <div>
            <a href="{% url 'core:cart_add' product.id%}" class="btn btn-cart border-0 rounded-5 py-3 px-4">
               <i class="fas fa-shopping-cart"></i>
              Add to cart
            </a>
            <a href="{% url 'core:add_to_wishlist' product.id %}" class="btn btn-cart border-0 rounded-5 py-3 px-4">
              <i class="fa-solid fa-heart"></i>
              Wishlist
            </a>
          </div>
        </div>
      </div>
    </div>

    {% empty %}

    <div class="col text-center">
      <div class="card rounded-2 border-0">
        <div class="card-body">
          <h3>Nothing found!!</h3>
        </div>
      </div>
    </div>
    {% endfor %}
    <!-- end product section -->
  </div>
</div>

templates/shop/product_review_add.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Add Product Review</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>
  <div class="row g-3">
    <div class="col-lg-6">
      <div class="card">
        <img src="{{product.image.url}}" alt="" class="card-img-top" />
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description}}</p>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <form action="" method="post">
            {% csrf_token %} {{form.as_p}}
            <button class="btn btn-primary rounded-5 px-4 py-3 me-2">
              Add
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end products -->
{% endblock content %}

templates/shop/shop.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Products</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row product-lists">{% include "shop/product_list.html" %}</div>

  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="pagination-wrap">
        <ul>
          {% if page_obj.has_previous %}
          <li><a href="?page=1">First</a></li>

          <li>
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Prev</a>
          </li>

          {% endif %}

          <li>
            <a class="active" href="#">{{ page_obj.number|default:0 }}</a>
          </li>

          {% if page_obj.has_next %}

          <li>
            <a href="?page={{ page_obj.next_page_number }}">&raquo; Next</a>
          </li>
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- end products -->
{% endblock content %}

templates/shop/wishlist_add.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Add to Whishlist</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>
  <div class="row g-3">
    <div class="col-lg-6">
      <div class="card">
        <img src="{{product.image.url}}" alt="" class="card-img-top" />
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description}}</p>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <form action="" method="post">
        {% csrf_token %}
        <div class="row row-cols-auto g-2 mb-3">
          {% for wishlist in wishlists %}

          <div class="col-auto">
            <div class="card rounded-pill">
              <div class="card-body">
                <div
                  class="form-check d-flex align-items-center justify-content-start"
                >
                  <input
                    class="form-check-input me-2"
                    type="checkbox"
                    name="wishlists"
                    value="{{wishlist.id}}"
                    id="id_wishlist_{{wishlist.id}}"
                    {%
                    if
                    product
                    in
                    wishlist.products.all
                    %}
                    checked="true"
                    {%
                    endif
                    %}
                  />
                  <label
                    class="form-check-label text-nowrap"
                    for="id_wishlist_{{wishlist.id}}"
                  >
                    <a href="{% url 'core:wishlist_detail' wishlist.id %}"
                      >{{wishlist.name}}</a
                    >
                  </label>
                </div>
              </div>
            </div>
          </div>

          {% empty %}
          <h5>No wishlist found</h5>
          {% endfor %}
        </div>
        <div class="mb-3">
          <a
            href="{% url 'core:wishlist_create' %}"
            class="btn btn-dark rounded-5 px-4 py-3"
            >Create now</a
          >
        </div>
        <hr />
        <button class="btn btn-primary rounded-5 px-4 py-3 me-2">Update</button>
        <a href="{% url 'core:shop' %}" class="btn btn-dark rounded-5 px-4 py-3"
          >Shop</a
        >
      </form>
    </div>
  </div>
</div>
<!-- end products -->
{% endblock content %}

templates/shop/wishlist_create.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Create Whishlist</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <form action="" method="post">
            {% csrf_token %} {{form.as_p}}
            <button class="btn btn-dark rounded-5 px-4 py-3">Create</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end products -->
{% endblock content %}

templates/shop/wishlist_detail.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Whishlist Details</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col">
      <h4 class="d-flex justify-content-between">
        {{wishlist.name}}
        <span class="h5">
<<<<<<< HEAD
          <a href="{% url 'core:shop' %}"  class="btn btn-dark rounded-pill px-4 py-3 text-uppercase">Back to shop</a>
=======
          <a href="{% url 'core:shop' %}">Back to shop</a>
>>>>>>> refs/remotes/origin/main
        </span>
      </h4>
      <div class="hr"></div>
    </div>
  </div>

  <div class="row product-lists">
    {% for product in wishlist.products.all %}

    <!-- product section -->
    <div class="col-lg-4 col-md-6 text-center">
      <div class="card">
        <a href="{% url 'core:product_detail' product.id %}">
          <img class="card-img-top" src="{{product.image.url}}" alt="" />
        </a>
        <div class="card-body">
          <h3>{{product.name}}</h3>
          <p class="product-price">
            <span>Per {{product.unit}}</span>
            <i class="fa-solid fa-inr"></i>
            {{product.price}}
          </p>
          
          <div>
            <a href="{% url 'core:cart_add' product.id%}" class="btn btn-cart border-0 rounded-5 py-3 px-4">
              <i class="fas fa-shopping-cart"></i>
              Add to cart
            </a>
            <a href="{% url 'core:add_to_wishlist' product.id %}" class="btn btn-cart border-0 rounded-5 py-3 px-4">
              <i class="fa-solid fa-remove"></i>
              Remove
            </a>
          </div>
        </div>
      </div>
    </div>

    {% empty %}

    <div class="col text-center">
      <div class="card rounded-2 border-0">
        <div class="card-body">
          <h3>Nothing found!!</h3>
          <p>
            <a href="{% url 'core:shop' %}">Back to shop</a>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
    <!-- end product section -->
  </div>

  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="pagination-wrap">
        <ul>
          {% if page_obj.has_previous %}
          <li><a href="?page=1">First</a></li>

          <li>
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Prev</a>
          </li>

          {% endif %}

          <li>
            <a class="active" href="#">{{ page_obj.number|default:0 }}</a>
          </li>

          {% if page_obj.has_next %}

          <li>
            <a href="?page={{ page_obj.next_page_number }}">&raquo; Next</a>
          </li>
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- end products -->
{% endblock content %}

templates/shop/wishlist_list.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<section class="vh-100">
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Whishlists</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row row-cols-auto g-2 g-lg-3 justify-content-center">
    {% for wishlist in wishlists %}

    <div class="col-auto">
      <div class="card rounded-pill">
        <div
          class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
        >
          <h6 class="card-title first-letter-danger">
            <a
            href="{% url 'core:wishlist_detail' wishlist.id %}"
              class="link-dark"
            >
              {{wishlist.name|upper}}
            </a>
          </h6>
          <p class="card-text">{{wishlist.description}}</p>
        </div>
      </div>
    </div>
   
    {% empty %}
    <h4>Nothing Found!!</h4>
    {% endfor %}
  </div>

  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="pagination-wrap">
        <ul>
          {% if page_obj.has_previous %}
          <li><a href="?page=1">First</a></li>

          <li>
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Prev</a>
          </li>

          {% endif %}

          <li>
            <a class="active" href="#">{{ page_obj.number|default:0 }}</a>
          </li>

          {% if page_obj.has_next %}

          <li>
            <a href="?page={{ page_obj.next_page_number }}">&raquo; Next</a>
          </li>
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <a href="{% url 'core:shop' %}" class="btn btn-dark rounded-pill px-4 py-2">Shop</a>
      <a href="{% url 'core:home' %}" class="btn btn-dark rounded-pill px-4 py-2">Back To Home</a>
    </div>
  </div>
</div>
</section>
<!-- end products -->
{% endblock content %}