core/urls.py
from django.urls import path, include
from core import views
from core import views as core_views

app_name = "core"

urlpatterns = [

    #comman
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("feedback/create/", views.FeedbackCreateView.as_view(), name="feedback_create"),
    path("shop/", views.ShopView.as_view(), name="shop"),


    # User
    path("user/profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path("user/profile/<int:pk>/detail/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path("user/profile/<int:pk>/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("user/profile/<int:pk>/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    #path("user/address/create/", views.AddressCreateView.as_view(), name="address_create"),
    path("user/dashboard/", views.DashboardView.as_view(), name="dashboard"),


    #cart
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/product/<int:pk>/add/", views.AddToCartView.as_view(), name="cart_add"),
    path("cart/checkout/", views.CheckoutView.as_view(), name="checkout"),


    #product
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("product/<int:pk>/detail/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product/category", views.CategoryListView.as_view(), name="category_list"),
    path("product/category/<int:pk>/product/", views.ProductListByCategory.as_view(), name="product_by_category"),
    path("product/<int:pk>/review/", views.ProductReviewAddView.as_view(), name="add_product_review"),

    #product search
    path("product/search/", core_views.SearchView.as_view(), name= "product_search"),


    # Wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist_list"),
    path("wishlist/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlist/<int:pk>/", views.WishlistDetailView.as_view(), name="wishlist_detail"),
    path("wishlist/add/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="add_to_wishlist"),
    path("wishlist/remove/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="remove_from_wishlist"),

    #registration
    path("user/signup/", views.RegistrationView.as_view(), name="signup"),
    path("user/login/", views.LoginView.as_view(), name="login"),
    path("user/logout/", views.LogoutView.as_view(), name="logout"),
    
    # Password Reset
    path("user/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("user/password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("user/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user/reset/done/", views.PasswordResetConfirmView.as_view(), name="password_reset_complete"),

    #order
    path("order/", views.OrderView.as_view(), name="order"),
    path("order/history/", views.OrderHistoryView.as_view(), name="order_history"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_detail"),

  # Payment
    path("payment/", views.PaymentView.as_view(), name="payment"),
    path("paymentlist/", views.PaymentListView.as_view(), name="payment_list"),
    path("payment/response/", views.payment_handler, name="payment_handler"),


    

]

ecart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path('accounts/', include('allauth.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/user/dashboard.html
{% extends 'base.html' %} {% block content %}

<!-- dashboard start -->
<section class="vh-100">
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Dashboard</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row row-cols-auto g-2 g-lg-3 justify-content-center">
    <!-- Items in cart start -->
    <div class="col-auto">
      <a href="{% url 'core:cart' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{cart.items.count}}</span
              >
            </h4>
            <h6 class="card-title">Items</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- Items in cart end -->

    <!-- Orders start -->
    <div class="col-auto">
      <a href="{% url 'core:order' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{orders.count}}</span
              >
            </h4>
            <h6 class="card-title">Orders</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- Orders end -->

    <!-- payments start -->
    <div class="col-auto">
      <a href="{% url 'core:payment_list' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{payments.count}}</span
              >
            </h4>
            <h6 class="card-title first-letter-danger">Payments</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- payments start -->

    <!-- wishlist start -->
    <div class="col-auto">
      <a href="{% url 'core:wishlist_list' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{user.wishlistmodel_set.count}}</span
              >
            </h4>
            <h6 class="card-title">Wishlist</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- wishlist end -->
    <!-- Order Delivered start -->
    <div class="col-auto">
      <a href="">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary">0</span>
            </h4>
            <h6 class="card-title first-letter-danger">
              <a href="" class="link-dark">Order Delivered</a>
            </h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- Order Delivered end -->
  </div>

  <div class="row">
    <div class="col">
      <a href="{% url 'core:shop' %}" class="btn btn-dark rounded-pill px-4 py-2">Shop</a>
    </div>
  </div>
</div>
</section>
<!-- end dashboard -->
{% endblock content %}

templates/user/profile.html
{% extends 'base.html' %} {% block content %}

<!-- cart -->
<div class="cart-section">
  <div class="container py-5">
    <div class="row justify-content-center mt-3 mb-3">
      <div class="col-auto">
        <div class="heading-1">
          <h1 class="text-center">Profile</h1>
          <div class="hl"></div>
        </div>
      </div>
    </div>
    <div class="row g-3 align-items-lg-start">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <img
              src="{{profile_form.instance.image.url}}"
              class="card-img"
              alt=""
            />
            <a href="{{profile_form.instance.image.url}}" download> Downlod This Image</a>
          </div>
        </div>
      </div>
      
      <div class="col-lg-6">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-title">About Me</h5>
              {{profile_form.as_p}}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-title">Address</h5>

              {{address_form.as_p}}
            </div>
          </div>
          <button
            type="submit"
            class="btn btn-dark rounded-5 px-4 py-3 text-uppercase"
          >
            Update
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- end cart -->
{% endblock content %}